In [1]:
import pandas as pd
import numpy as np

In [2]:
## Importing from hard coded sources
## TODO make the sources dynamic to user input
fuel_df = pd.read_excel(r"C:\Users\David's PC\OneDrive - Grand Canyon University\Capstone\Data Sources\EIA\Table_9.4_Retail_Motor_Gasoline_and_On-Highway_Diesel_Fuel_Prices.xlsx",
                        header=11)

In [3]:
## Get access to s3 bucket

import pandas as pd
import boto3

ACCESS=pd.read_csv(r"C:\Users\David's PC\OneDrive - Grand Canyon University\Capstone\AWS\Access\jupyters3access.csv")

AWS_S3_BUCKET="capstoneds2022data"
AWS_ACCESS_KEY_ID=ACCESS['Access key ID'].values[0]
AWS_SECRET_ACCESS_KEY=ACCESS['Secret access key'].values[0]


s3=boto3.resource('s3',
                  aws_access_key_id=AWS_ACCESS_KEY_ID,
                  aws_secret_access_key=AWS_SECRET_ACCESS_KEY)
s3.Bucket(AWS_S3_BUCKET).download_file('Data Sources/EIA/Table_9.10_Natural_Gas_Prices.xlsx', 
                                       r"C:\Users\David's PC\OneDrive - Grand Canyon University\Capstone\Data Sources\tmp\natural_gas")

In [4]:
natural_gas_df = pd.read_excel(r"C:\Users\David's PC\OneDrive - Grand Canyon University\Capstone\Data Sources\tmp\natural_gas",
                               header=11)
natural_gas_df

,Unnamed: 0,(Dollars per Thousand Cubic Feet),(Dollars per Thousand Cubic Feet).1,(Dollars per Thousand Cubic Feet).2,(Percent),(Dollars per Thousand Cubic Feet).3,(Percent).1,(Dollars per Thousand Cubic Feet).4,(Percent).2,(Dollars per Thousand Cubic Feet).5,(Dollars per Thousand Cubic Feet).6,(Percent).3
0,1976-01-01,0.54,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
1,1976-02-01,0.54,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
2,1976-03-01,0.54,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
3,1976-04-01,0.55,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
4,1976-05-01,0.55,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
...,...,...,...,...,...,...,...,...,...,...,...,...
547,2021-08-01,Not Available,5.67,20.98,96.5,10.19,54.7,5.01,13,Not Available,4.45,86.3
548,2021-09-01,Not Available,6.25,20.25,96.6,10.28,56.4,5.57,13.7,Not Available,5.09,87.9
549,2021-10-01,Not Available,6.41,17.5,97.1,10.45,59.5,6.84,13.4,Not Available,5.75,87.8
550,2021-11-01,Not Available,6.03,13.29,97,10.11,65.5,7.03,13.7,Not Available,5.89,87.2
551,2021-12-01,Not Available,5.81,13.13,96.7,10.33,68.3,6.74,14,Not Available,5.15,88.7

In [6]:
import pandasgui
from pandasgui import show
import PyQt5.QtWebEngineWidgets

gas_gui=show(natural_gas_df)

PandasGUI INFO â€” pandasgui.gui â€” Opening PandasGUI